
apiVersion: v1
kind: Service
metadata:
  name: odoo-stemdo
  labels:
    app: odoo 
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: odoo
