
apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-db-config
  namespace: odoo-community  
  labels:
    app: odoo
data:
  HOST: *****
  USER: ****
  PASSWORD: ****


apiVersion: v1
kind: ConfigMap
metadata:
  name: odoo-db-config
  namespace: odoo-community  
  labels:
    app: odoo
data:
  HOST: ****
  USER: ****
  PASSWORD: ****