apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: odoo
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
        - name: odoo
          imagePullPolicy: Always
          # image: odoo:17.0
          # image: sebasnaa/custom_odo:17
          image: sebasnaa/custom_odo:stemdo17
          ports:
            - containerPort: 8069
          envFrom:
            - configMapRef:
                name: odoo-db-config
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo
            - mountPath: /etc/odoo/odoo.conf
              subPath: odoo.conf
              name: odoo-config-volume      
      initContainers:
        - name: odoo-permissions
          image: debian:bullseye-slim
          command: ['chown', "101:101", "-R", "/var/lib/odoo"]
          volumeMounts:
            - mountPath: /var/lib/odoo
              name: odoo
      volumes:
        - name: odoo
          persistentVolumeClaim:
            claimName: odoo-pv-claim
        - name: odoo-config-volume
          configMap:
            name: odoo-config
