apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "odoo-helm-chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    reloader.stakater.com/match: "true"   # Anotación para Reloader
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        reloader.stakater.com/match: "true"  # Aseguramos la anotación en el pod template
    spec:
      containers:
        - name: odoo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8069
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: PASSWORD
          volumeMounts:
            - mountPath: /etc/odoo/odoo.conf
              subPath: odoo.conf
              name: odoo-config-volume
      volumes:
        - name: odoo-config-volume
          configMap:
            name: {{ .Values.odooConfig.name }}
