apiVersion: v1
kind: Service
metadata:
  name: {{ include "odoo-helm-chart.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ .Chart.Name }}
